comments:
  blockComment:
    - "<!"
    - "!>"
brackets:
  - ["<[", "]>"]
  - ["[", "]"]
  - ["<!", "!>"]
  - ["{{", "}}"]
  - ["{%", "%}"]
  - ["<%", "%>"]
  - ["<?", "?>"]
  - ["{", "}"]
  - ["<(", ")>"]
  - ["<#", "#>"]
  - ["</", "/>"]
  - ["<_", "_>"]
  - ["<~", "~>"]
  - ['<"', '">']
  - ["<`", "`>"]
colorizedBracketPairs:
  - ["{", "}"]
  - ["<(", ")>"]
  - ["<#", "#>"]
  - ["</", "/>"]
  - ["<_", "_>"]
  - ["<~", "~>"]
  - ['<"', '">']
  - ["<`", "`>"]
autoClosingPairs:
  - ["{", "}"]
  - ["[", "]"]
  - ["#[", "]#"]
  - ["##[", "]##"]
  - ["<", ">"]
  - ["(", ")"]
surroundingPairs:
  - ["{", "}"]
  - ["[", "]"]
  - ["(", ")"]
  - ["<", ">"]
  - ['"', '"']
  - ["'", "'"]
  - ["`", "`"]
